### ISSUE TITLE
Practica#2- BACK-END

### ISSUE THREAD

**Issue by MariaC232** [SistemasTecTlaxiaco/practica-back-end-cb-24h#2]
[Practica 2_Back-End.pdf](https://github.com/SistemasTecTlaxiaco/practica-back-end-cb-24h/files/6549415/Practica.2_Back-End.pdf)

**Comment by Anthony4523** [comment]
Buen trabajo

Calificación: 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
